[window]
opacity = 0.91
padding.x = 5
padding.y = 5
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
size = 13.0
