[window]
opacity = 0.91
padding.x = 5
padding.y = 5
decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "Both"

[font]
normal.family = "Ubuntu Sans Mono"
normal.style = "Medium"
bold.family = "Ubuntu Sans Mono"
bold.style = "Bold"
italic.family = "Ubuntu Sans Mono"
italic.style = "MediumItalic"
bold_italic.family = "Ubuntu Sans Mono"
bold_italic.style = "BoldItalic"
size = 13

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500

[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

[colors.cursor]
text = '#181818'
cursor = '#d8d8d8'

[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
