#!/bin/bash
## install essential tools for my development environment
## -----
set -e
is_mac=0
if [[ "$OSTYPE" == "darwin"* ]]; then
  is_mac=1
elif [[ "$OSTYPE" != "linux-gnu" ]]; then
  echo 'unsupported os.'
  exit
fi

echo '[-] installing some prerequisite packages [-]'
if [[ $is_mac -eq 1 ]]; then
  echo '[-] installing xcode command line tools [-]'
  xcode-select --install
  if ! hash brew &> /dev/null; then
    echo '[-] installing homebrew [-]'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  brew update
  brew install curl wget git coreutils watch ncdu
else
  sudo apt update
  sudo apt upgrade -y
  sudo apt install -y curl wget zip zsh git sway coreutils watch ncdu
fi

echo '[-] installing favourite font [-]'
if [[ $is_mac -eq 1 ]]; then
  brew install --cask font-jetbrains-mono
else
  wget 'https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip'
  mkdir -p ~/.local/share/fonts
  unzip JetBrainsMono-2.304.zip -d ~/.local/share/fonts
  rm -f JetBrainsMono-2.304.zip
  fc-cache -f -v
fi

function linking() {
  ln -sfn $(pwd)/.zshrc ~/.zshrc
  ln -sfn $(pwd)/.zshenv ~/.zshenv
  ln -sfn $(pwd)/.gitignore ~/.gitignore
  ln -sfn $(pwd)/.fdignore ~/.fdignore
  ln -sfn $(pwd)/.vimrc ~/.vimrc
  ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -sfn $(pwd)/nvim $XDG_CONFIG_HOME/nvim
  ln -sfn $(pwd)/ghostty $XDG_CONFIG_HOME/ghostty

  if [[ $is_mac -eq 1 ]]; then
    ln -sfn $(pwd)/aerospace $XDG_CONFIG_HOME/aerospace
  else
    ln -sfn $(pwd)/sway $XDG_CONFIG_HOME/sway
  fi
}
echo '[-] linking dotfiles [-]'
linking

echo '[-] installing extended packages [-]'
if [[ $is_mac -eq 1 ]]; then
  brew install zsh-autosuggestions parallel fzf fd ripgrep jq
  brew install httpie pyenv universal-ctags
else
  sudo apt install -y zsh-autosuggestions parallel fzf fd-find ripgrep jq httpie universal-ctags
  mkdir -p ~/.local/bin
  ln -sfn $(which fdfind) ~/.local/bin/fd
fi

echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

echo '[-] creating essential directories [-]'
mkdir -p ~/personal
mkdir -p ~/repos
mkdir -p ~/opensource

echo '[-] installing ghostty [-]'
if [[ $is_mac -eq 1 ]]; then
  brew install ghostty
else
  git clone https://github.com/ghostty-org/ghostty ~/opensource/ghostty
  # cd ~/opensource/ghostty
  # git checkout v1.1.2
  # sudo apt install -y gtk4 libadwaita pkg-config
  # zig build -p ~/.local -Doptimize=ReleaseFast
fi

echo '[-] installing neovim [-]'
git clone https://github.com/neovim/neovim ~/opensource/neovim

echo '[-] change default shell to zsh [-]'
chsh -s $(which zsh)
echo '[-] Setup done. Run `source ~/.zshrc` to refresh shell config [-]'
