#!/bin/bash
# install essential tools for my mac development environment
# vim: ft=bash
# -----
set -e

echo '[-] installing xcode command line tools [-]'
xcode-select --install
if ! hash brew &> /dev/null; then
  echo '[-] installing homebrew [-]'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
brew update
brew install curl wget git coreutils watch ncdu cmake ninja

echo '[-] installing favourite fonts [-]'
brew install --cask font-ubuntu-sans font-ubuntu-sans-mono

function linking() {
  ln -sfn $(pwd)/.zshrc ~/.zshrc
  ln -sfn $(pwd)/.zshenv ~/.zshenv
  ln -sfn $(pwd)/.tmux.conf ~/.tmux.conf
  ln -sfn $(pwd)/.psqlrc ~/.psqlrc
  ln -sfn $(pwd)/.vimrc ~/.vimrc
  ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -sfn $(pwd)/alacritty $XDG_CONFIG_HOME/alacritty

  ln -sfn $(pwd)/.gitignore ~/.gitignore
  git config --global core.excludesFile '~/.gitignore'
}
echo '[-] linking dotfiles [-]'
linking

echo '[-] installing extended packages [-]'
brew install parallel tmux fzf ripgrep jq httpie universal-ctags golang npm
npm config set prefix ~/.npm

echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

echo '[-] downloading vim plugin manager [-]'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

target_dir=~/.zsh/zsh-autosuggestions
if [ ! -d "$target_dir" ] ; then
  echo '[-] cloning zsh-autosuggestions [-]'
  git clone https://github.com/zsh-users/zsh-autosuggestions $target_dir
fi

echo '[-] creating essential directories [-]'
mkdir -p ~/personal
mkdir -p ~/repos
mkdir -p ~/opensource

echo '[-] installing alacritty [-]'
brew install alacritty

echo '[-] Setup done. Run `source ~/.zshrc` to refresh shell config [-]'
