#!/bin/bash
# install essential tools for my mac development environment
# vim: ft=bash
# -----
set -e

echo '[-] installing xcode command line tools [-]'
xcode-select --install
if ! hash brew &> /dev/null; then
  echo '[-] installing homebrew [-]'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi
brew update
brew install curl wget git coreutils watch ncdu cmake ninja

function linking() {
  ln -sfn $(pwd)/.zshrc ~/.zshrc
  ln -sfn $(pwd)/.zshenv ~/.zshenv
  ln -sfn $(pwd)/.tmux.conf ~/.tmux.conf
  ln -sfn $(pwd)/.psqlrc ~/.psqlrc
  ln -sfn $(pwd)/.vimrc ~/.vimrc
  ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -sfn $(pwd)/alacritty $XDG_CONFIG_HOME/alacritty
  ln -sfn $(pwd)/nvim $XDG_CONFIG_HOME/nvim

  mkdir -p ${XDG_DATA_HOME:=~/.local/share}
  mkdir -p $XDG_DATA_HOME/nvim/site
  ln -sfn $(pwd)/pack $XDG_DATA_HOME/nvim/site/pack

  ln -sfn $(pwd)/.gitignore ~/.gitignore
  git config --global core.excludesFile '~/.gitignore'
}
echo '[-] linking dotfiles [-]'
linking

echo '[-] creating essential directories [-]'
mkdir -p ~/personal
mkdir -p ~/repos
mkdir -p ~/opensource

echo '[-] installing extended packages [-]'
brew install parallel tmux ripgrep jq universal-ctags golang

echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.zsh/plugins/git/git-prompt.sh

target_dir=~/.zsh/zsh-autosuggestions
if [ ! -d "$target_dir" ] ; then
  echo '[-] cloning zsh-autosuggestions [-]'
  git clone https://github.com/zsh-users/zsh-autosuggestions $target_dir
fi

echo '[-] installing favourite font [-]'
brew install --cask font-hack-nerd-font

echo '[-] installing alacritty [-]'
brew install alacritty

target_dir=~/opensource/neovim
if [ ! -d "$target_dir" ] ; then
  echo '[-] building neovim [-]'
  git clone https://github.com/neovim/neovim.git $target_dir
  cd $target_dir
  # git checkout nightly
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
fi

echo '[-] device ready, restart your computer. [-]'
