#!/usr/bin/env bash
# install essential tools for my unix-like development environment
# vim: ft=bash
# -----
set -e

if [[ "$OSTYPE" == "darwin"* ]]; then
  if ! xcode-select -p &> /dev/null; then
    echo '[-] installing xcode command line tools [-]'
    xcode-select --install
  fi
  if ! hash brew &> /dev/null; then
    echo '[-] installing homebrew [-]'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  echo '[-] installing prerequisite packages [-]'
  brew update
  brew install curl wget git coreutils watch ncdu cmake ninja tree
  brew install parallel tmux fzf ripgrep jq golang htop pdfgrep tldr hyperfine procs
  brew install maccy universal-ctags

  echo '[-] installing favourite font [-]'
  brew install --cask font-hack
else
  echo '[-] installing prerequisite packages [-]'
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y curl wget zip zsh git coreutils gcc clang cmake make ninja-build
  sudo apt install -y watch ncdu make autoconf automake parallel vim tmux fzf ripgrep jq
  sudo apt install -y tree htop pdfgrep tldr hyperfine procs universal-ctags
fi

function linking() {
  ln -sfn $(pwd)/.zshrc ~/.zshrc
  ln -sfn $(pwd)/.zshenv ~/.zshenv
  ln -sfn $(pwd)/.tmux.conf ~/.tmux.conf
  ln -sfn $(pwd)/.psqlrc ~/.psqlrc
  ln -sfn $(pwd)/.vimrc ~/.vimrc
  ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc
  ln -sfn $(pwd)/.gitignore ~/.gitignore
  git config --global core.excludesFile '~/.gitignore'
}
echo '[-] linking dotfiles [-]'
linking

echo '[-] creating essential directories [-]'
mkdir -p ~/personal
mkdir -p ~/repos
mkdir -p ~/opensource
touch ~/.profile

echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
  -o ~/.zsh/plugins/git/git-prompt.sh

target_dir=~/.zsh/zsh-autosuggestions
if [ ! -d "$target_dir" ] ; then
  echo '[-] cloning zsh-autosuggestions [-]'
  git clone https://github.com/zsh-users/zsh-autosuggestions $target_dir
else
  cd $target_dir
  git pull --rebase
fi

echo '[-] downloading vim plugin manager [-]'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

current_shell=$(echo $SHELL)
if [ "$current_shell" != "/usr/bin/zsh" ]; then
  echo '[-] change default shell to zsh [-]'
  chsh -s $(which zsh)
  echo '[-] device ready, restart your computer. [-]'
fi
