#!/bin/sh

## Internal variables
readonly _SWAY_COMMAND="/usr/bin/sway"
SWAY_EXTRA_ARGS=""

## General exports
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

## Apply `environment.d(5)` customizations
# This can be used to share the custom environment configs with systemd --user.
# Importing `systemd --user show-environment` here may have unexpected
# consequences, such as getting a leftover `WAYLAND_DISPLAY` or `DISPLAY`
# and breaking Sway startup. Thus, the direct call to a systemd generator.
set -o allexport
eval "$(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)"
set +o allexport

## Load Sway-specific user environment customizations
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment" ]; then
    set -o allexport
    # shellcheck source=/dev/null
    . "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment"
    set +o allexport
fi

## Unexport internal variables
# export -n is not POSIX :(
_SWAY_EXTRA_ARGS="$SWAY_EXTRA_ARGS"
unset SWAY_EXTRA_ARGS

## Log all exported WLR_ variables
if _WLR_VARS=$(env | grep '^WLR_'); then
    printf 'environment variables for wlroots: %s' "$_WLR_VARS" |
        tr '\n' ' ' |
        systemd-cat -p notice -t "${_SWAY_COMMAND##*/}"
fi

# Start sway with extra arguments and send output to the journal
# shellcheck disable=SC2086 # quoted expansion of EXTRA_ARGS can produce empty field
exec systemd-cat -- $_SWAY_COMMAND $_SWAY_EXTRA_ARGS "$@"
