return {
  "folke/trouble.nvim",
  opts = {
    icons = {
      indent        = {
        top         = "│ ",
        middle      = "├╴",
        last        = "└╴",
        fold_open   = " ",
        fold_closed = " ",
        ws          = " ",
      },
      folder_closed = "\\",
      folder_open   = "/",
      kinds         = {
        Array         = "",
        Boolean       = "",
        Class         = "",
        Constant      = "",
        Constructor   = "",
        Enum          = "",
        EnumMember    = "",
        Event         = "",
        Field         = "",
        File          = "",
        Function      = "",
        Interface     = "",
        Key           = "",
        Method        = "",
        Module        = "",
        Namespace     = "",
        Null          = "",
        Number        = "",
        Object        = "",
        Operator      = "",
        Package       = "",
        Property      = "",
        String        = "",
        Struct        = "",
        TypeParameter = "",
        Variable      = "",
      },
    },
  },
  cmd = "Trouble",
  keys = {
    { "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", },
    { "<leader>xb", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", },
    { "<leader>xs", "<cmd>Trouble symbols toggle focus=true<cr>", },
  },
}
