#!/bin/bash
#vim:ft=bash
dir=$(find ~/personal ~/repos ~/opensource -type d -maxdepth 3 | fzf --tmux)
if [ -z "${dir}" ]; then
  exit 0
fi
name=$(basename "$dir")
if ! tmux has-session -t $name 2>/dev/null; then
  tmux new-session -s $name -d -c $dir
  tmux send-keys -t $name 'nvim .' c-m
fi
tmux switch -t $name
